### QUE:-1 Demonstrate three different methods for creating identical 2D arrays in NumPy Provide the code for each method and the final output after each method

In [2]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr2=np.ones((2,3))
print(arr2)

In [ ]:
arr3=np.zeros((2,3))
print(arr3)

In [ ]:
arr4=np.full((2,3),5)
print(arr4)

### QUE:-2 Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array

In [ ]:
arr=np.linspace(1,10,100)
print("this is 1d array\n")
print(arr)
arr_2d=arr.reshape((10,10))
print("\nthis is 2d array\n")
print(arr_2d)

### QUE:-3 Explain the following termsg  1.The difference in nparray, npasarray and npasanyarrayX  2.The difference between Deep copy and shallow copy.

## numpy.array() creates a new array from any object exposing the array interface, or from any nested sequence. It always returns a new array, even if the input is already a NumPy array, unless the copy=False parameter is specified and the input is a NumPy array.

## numpy.asarray() converts the input to a NumPy array, but unlike numpy.array(), it does not create a copy if the input is already a NumPy array. This can be more efficient when you don't need a copy.

## numpy.asanyarray() is similar to numpy.asarray(), but it preserves subclasses of ndarray. This means if the input is an instance of a subclass of ndarray (like numpy.matrix or numpy.ma.MaskedArray), numpy.asanyarray() will return an object of the same subclass.



# deep copy and shallow copy:-

# Shallow Copy:

## Creates a new object, but references the same nested objects.
## Changes to nested objects affect both the original and the copy.
## Faster and less memory-intensive.
## Use the view() method in NumPy.


# Deep Copy:

## Creates a new object and recursively copies all nested objects.
## Changes to nested objects do not affect the original object.
## Slower and more memory-intensive.
## Use the copy() method in NumPy.

--------------------------------------------------------------------------------------------------------------------------------------

### QUE:-4 Generate a 3*3  array with random floating-point numbers between 2 and 20 then, round each number in the array to 2 decimal places .

In [ ]:
random_arr=np.random.uniform(2,20,(3,3))
round_arr=np.round(random_arr,2)
print(random_arr)
print(round_arr)

### QUE:-5 Create a NumPy array with random integers between 1 and 10 of shape (5,6 ))  After creating the array perform the following operations:

 ### a)Extract all even integers from array.

### b)Extract all odd integers from array

In [ ]:
arr=np.random.randint(1,10,(5,6))
print(arr)
arr_even=arr[arr%2==0]
print("even numbers")
print(arr_even)
arr_odd=arr[arr%2==1]
print("odd numbers")
print(arr_odd)

### QUE:-6 Create a 3D NumPy array of shape (3,3,3) containing random integers between 1 and 10 Perform the following operations:

 ### a) Find the indices of the maximum values along each depth level (third axis).

 ### b) Perform elementwise multiplication of between both array

In [ ]:
import numpy as np

arr=np.random.randint(1,11,(3,3,3))
print("this is arr")
print(arr)

max_index=np.argmax(arr,axis=2)
print("\nthis is max indecies")
print(max_index)

arr2=np.random.randint(1,11,(3,3,3))
print("\nthis is arr2")
print(arr2)

result=arr*arr2
print("\nthis is element wise multiplication")
print(result)

### QUE:-7 Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type Also display the table attributes and data types of each column

In [ ]:
import pandas as pd
df=pd.read_csv('People Data.csv')
print('before cleaning data')
print(df[['Phone']])
df['Phone']=df['Phone'].str.replace(r'\D','',regex=True)
df['Phone']=pd.to_numeric(df['Phone'],errors='coerce').astype('Int64')
print("\nafter cleaning data")
print(df['Phone'])
print("\ndataframe information")
print(df.info())

### QUE;-8 Perform the following tasks using people dataset:

### a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 ### b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

### c) Display the first 10 rows of the filtered dataset.

### d) Extract the ‘Salary’ column as a Series and display its last 5 valuesX

In [29]:
import pandas as pd
df=pd.read_csv("Data.csv")
df=df.iloc[50:]
#a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
print("data with skiping 50 rows\n")
print(df)

#b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
df=df[["Last Name","Gender","Phone","Salary"]]
print("\nonly specific column data read\n")
print(df)

#c) Display the first 10 rows of the filtered dataset.
print("\ndisplay only 10 rows\n")
print(df.head(10))

#d) Extract the ‘Salary’ column as a Series and display its last 5 values
print("\nseries column last 5 data\n")
print(df['Salary'].tail(5))
print(type(df['Salary'].tail(5)))

data with skiping 50 rows

     Index          User Id First Name Last Name  Gender  \
50      51  CccE5DAb6E288e5         Jo    Zavala    Male   
51      52  DfBDc3621D4bcec     Joshua     Carey  Female   
52      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
53      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
54      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                          Email                   Phone Date of birth  \
50         pamela64@example.net  001-859-448-9935x54536    23-11-1992   
51    dianashepherd@example.net    001-274-739-8470x814    07-01-1915   
52    ingramtiffany@example.org  

### QUE;-9 Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke',  'Gender' column contains the word Female and ‘salary’ should Pe less than 85000‚

In [53]:
import pandas as pd
df=pd.read_csv("Data.csv")
filterd=df[(df["Last Name"]=="Duke")&(df['Gender']=="Female")&(df['Salary']<85000)]
print(filterd)


     Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000  


### QUE:-10 Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [4]:
import pandas as pd
import numpy as np
rand_int=np.random.randint(1,7,35)
reshape=rand_int.reshape(7,5)
df=pd.DataFrame(reshape)
print(df)

   0  1  2  3  4
0  5  2  1  3  5
1  3  2  1  5  3
2  2  1  4  4  6
3  1  3  6  1  2
4  6  1  6  1  4
5  2  5  2  4  3
6  6  5  2  3  1


### QUE:-11 Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by 'joining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc&

In [15]:
import pandas as pd
import numpy as np
series1=pd.Series(np.random.randint(10,50,50))
print("\nthis is the first series\n")
#print(series1)
series2=pd.Series(np.random.randint(100,1000,50))
print("\nthis is the second series\n")
#print(series2)
df=pd.DataFrame({'col1':series1,'col2':series2})
print("\nthis is Datafrmae\n")
print(df)


this is the first series


this is the second series


this is Datafrmae

    col1  col2
0     36   782
1     45   271
2     40   542
3     30   314
4     46   864
5     14   111
6     31   783
7     22   233
8     49   776
9     27   605
10    26   365
11    40   844
12    34   568
13    30   393
14    19   934
15    39   356
16    48   246
17    26   630
18    38   879
19    48   695
20    30   186
21    23   330
22    21   280
23    46   303
24    15   615
25    20   594
26    35   440
27    27   978
28    34   217
29    32   489
30    24   232
31    34   416
32    16   505
33    46   135
34    30   347
35    17   393
36    39   872
37    11   943
38    35   502
39    49   190
40    39   954
41    14   235
42    25   162
43    49   963
44    37   756
45    14   243
46    42   128
47    10   701
48    46   363
49    48   761


### QQUE:-12 Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final output also&

In [45]:
df=pd.read_csv("Data.csv")
df.drop(['Email','Phone','Date of birth'] ,axis=1,inplace=True)

In [50]:
df.dropna(inplace=True)

In [48]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 7 columns]