### QUE:-1 . Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [41]:
import numpy as np

arr=np.array([0,1,2,3,4,5])
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [42]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


-----------------------------------------------------------------------------------------------------------------------------------

### QUE:-3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.



In [43]:
arr=np.array([3+5j,5+2j,9+2j], dtype=np.complex128)
print(arr)

[3.+5.j 5.+2.j 9.+2.j]


------------------------------------------------------------------------------------------------------------------------------------




### QUE:-4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [44]:
arr=np.array([0,1,2,3,4,5])
arr_float=arr.astype(np.float64)
print(arr_float)


[0. 1. 2. 3. 4. 5.]


-------------------------------------------------------------------------------------------------------------------------------

### QUE:-5.  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [45]:
arr=np.array([0,1,2,3,4,5], dtype=np.float64)
arr_float_32=arr.astype(np.float32)
print(arr_float_32)
print(arr_float_32.dtype)

[0. 1. 2. 3. 4. 5.]
float32


----------------------------------------------------------------------------------------------------------------------------------

### QUE:-6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [46]:
def array_attributes(arr):
    shape=arr.shape
    size=arr.size
    dtype=arr.dtype
    return shape,size,dtype

arr=np.array([[1,2,3],[4,5,6]])
shape,size,dtype=array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


----------------------------------------------------------------------------------------------------------------

### QUE:-7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [47]:
def array_dimension(arr):
    dimensions=arr.ndim
    return dimensions
arr=np.array([[1,2,3],[4,5,6]])
dimensions=array_dimension(arr)
print(dimensions)

2


-----------------------------------------------------------------------------------------------------------------

### QUE:-8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the totalsize in bytes.

In [48]:
def item_size_info(arr):
    item_size=arr.itemsize
    total_size=arr.nbytes
    
    return item_size,total_size
arr=np.array([[1,2,3],[4,5,6]])
item_size,total_size=item_size_info(arr)
print(item_size)
print(total_size)

8
48


-------------------------------------------------------------------------------------------------------------

### QUE:-9  Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [49]:
def array_strides(arr):
    strides=arr.strides
    return strides
arr=np.array([[1,2,3],[4,5,6]])
strides=array_strides(arr)
print(strides)

(24, 8)


----------------------------------------------------------------------------------------------------------

### QUE:-10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [50]:
def shape_stride_relationship(arr):
    shape=arr.shape
    stride=arr.strides
    return shape,strides

arr=np.array([[1,2,3],[4,5,6]])
shape,strides=shape_stride_relationship(arr)
print(shape)
print(strides)
                            

(2, 3)
(24, 8)


-------------------------------------------------------------------------------------------------------------

### QUE:-11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [51]:
def create_zeros_array(n):
    return np.zeros(n)
n=6
zeros_array=create_zeros_array(n)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]




--------------------------------------------------------------------------------------------------



### QUE:-12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [52]:
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))
rows=3
cols=4
ones_array=create_ones_matrix(rows,cols)
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


--------------------------------------------------------------------------------------------------------------

### QUE:-13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments andcreates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified`step`.

In [53]:
def generate_range_array(start,stop,step):
    array= np.arange(start,stop,step)
    array_list=array.tolist()
    return array_list
start=1
stop=20
step=2
array_list=generate_range_array(start,stop,step)
print(array_list)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


--------------------------------------------------------------------------------------------------------------


### QUE:-14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` asarguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).

In [54]:
def generate_linear_space(start,stop,num):
    array= np.linespace(start,stop,num)
    array_list=array.tolist()
    return array_list
start=1.0
stop=25.0
num=5
array_list=generate_range_array(start,stop,num)
print(array_list)

[1.0, 6.0, 11.0, 16.0, 21.0]


--------------------------------------------------------------------------------------------------------------


### QUE:-15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [55]:
def create_identity_matrix(n):
    return np.eye(n)
n=3
eye_matrix=create_identity_matrix(n)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


--------------------------------------------------------------------------------------------------------------

### QUE:-16 Write a function that takes a Python list and converts it into a NumPy array.

In [56]:

def list_numpy(lst):
    return np.array(lst)

lst=[1,2,3,4,5,6]
convert=list_numpy(lst)
print(convert)

    

[1 2 3 4 5 6]


--------------------------------------------------------------------------------------------------------------

### QUE:-17  Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [57]:
array=np.array([[1,2,3],[4,5,6]])
view=array.view()
view[0,0]=100
print(array)
print()
print(view)

[[100   2   3]
 [  4   5   6]]

[[100   2   3]
 [  4   5   6]]


--------------------------------------------------------------------------------------------------------------

### QUE:-18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [58]:
import numpy as np
def concatenates_array(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis=axis)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,4,6],[1,3,5]])
result=concatenates_array(arr1,arr2,axis=0)
print(result)

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [1 3 5]]


------------------------------------------------------------------------------------------------------------

### QUE:-19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

In [59]:
import numpy as np

# Create two arrays with different shapes
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])

arr2_t=np.transpose(arr2)

# Concatenate them horizontally
result = np.concatenate((arr1, arr2_t), axis=1)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated horizontally:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Concatenated horizontally:
[[ 1  2  3  7  9 11]
 [ 4  5  6  8 10 12]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-20  Write a function that vertically stacks multiple NumPy arrays given as a list.


In [60]:
def vertically_array(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

arr3 = np.array([[13, 14, 15],
                 [16, 17, 18]])

stacked_array = vertically_array([arr1, arr2, arr3])
print(stacked_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive)with a given step size.

In [61]:
def interger_array(start,stop,step):
    return np.arange(start,stop,step)
start=1
stop=20
step=2
int_arr=interger_array(start,stop,step)
print(int_arr)

[ 1  3  5  7  9 11 13 15 17 19]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).


In [62]:
def equal_space():
    return np.linspace(0,1,10)

linear=equal_space()
print(linear)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-23  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and1000 (inclusive).

In [63]:
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(start=0, stop=3, num=5)

result = generate_logarithmically_spaced_values()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the valuesare random integers between 1 and 100.

In [24]:
import numpy as np
import pandas as pd
data_array=np.random.randint(1,100,size=(5,3))
df=pd.DataFrame(data_array,columns=['column11','column2','column3'])
print(df)

   column11  column2  column3
0        67       99       38
1        96       80       80
2        72       76       90
3        77        3       71
4        83       74       80


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific columnwith zeros. Use NumPy operations within the Pandas DataFrame.

In [25]:
def negeive_remove(df):
    return df.applymap(lambda x : 0 if x < 0 else x)
data = {'A': [-1, 2, -3, 4, 5],
        'B': [6, -7, 8, -9, 10],
        'C': [11, 12, 13, 14, 15]}
df=pd.DataFrame(data)
print('original')
print(df)
df_modi=negeive_remove(df)
print("modified")
print(df_modi)

original
   A   B   C
0 -1   6  11
1  2  -7  12
2 -3   8  13
3  4  -9  14
4  5  10  15
modified
   A   B   C
0  0   6  11
1  2   0  12
2  0   8  13
3  4   0  14
4  5  10  15


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:_26 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [26]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element=arr[2]
print('third element=',third_element)

third element= 30


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [27]:
import numpy as np

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
element_=arr_2d[1,2]
print(element_)

6


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [28]:
import numpy as np
arr=arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5=arr[arr>5]
print(greater_than_5)

[ 8 10  7]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9])
sliced=arr[2:6]
print(sliced)

[3 4 5 6]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])


In [30]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sliced=arr_2d[0:2,1:3]
print(sliced)

[[2 3]
 [5 6]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-31 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [31]:
import numpy as np
def extract_element(arr_2d,indices):
    return arr_2d[indices]

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
indices=np.array([2,0,1])
extracted_elements = extract_element(arr_2d, indices)

print(extracted_elements)

[[7 8 9]
 [1 2 3]
 [4 5 6]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-32. Create a NumPy function that filters elements greater than a threshold from a given 1D array usingboolean indexing

In [32]:
def filter_greater_than(arr,threshold):
    return arr[arr>threshold]
arr=np.array([1,2,3,4,5,6,7,8,9])
threshold=4
result=filter_greater_than(arr,threshold)
print(result)
    

[5 6 7 8 9]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [33]:
def extract_array(arr_3d,indices1,indices2,indices3):
    return arr_3d[indices1,indices2,indices3]
arr_3d= np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

indices1 = np.array([0, 1, 2])
indices2 = np.array([1,0,0])
indices3 = np.array([2,0,1])

extracted_element=extract_array(arr_3d,indices1,indices2,indices3)
print(extracted_element)

[ 6 10 20]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-34. Write a NumPy function that returns elements from an array where both two conditions are satisfiedusing boolean indexing.

In [34]:
def filter_element(arr,cond1,cond2):
    return arr[(cond1)&(cond2)]
arr=np.array([1,2,3,4,5,6,7,8,9,12,13,14,15])
cond1=arr>4
cond2=arr%2==0
result=filter_element(arr,cond1,cond2)
print(result)

[ 6  8 12 14]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-35. Create a NumPy function that extracts elements from a 2D array using row and column indices providedin separate arrays.

In [35]:
import numpy as np
def extract_array(arr,row,column):
    return arr[row,column]
arr=np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
row=np.array([0,1,2])
column=np.array([1,0,2])
extracted_array=extract_array(arr,row,column)
print(extracted_array)

[2 4 9]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [36]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result=arr+5
print("original_array")
print(arr)
print("scalar_value")
print(result)

original_array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
scalar_value
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [37]:
arr1 = np.array([[2, 3, 4]])  
arr2 = np.array([[1, 2, 3, 4],  
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
arr1_reshape=np.transpose(arr1)

result = arr1_reshape * arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after multiplication:")
print(result)


Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [38]:
import numpy as np


arr1 = np.array([[2, 3, 4, 5]])  #
arr2 = np.array([[1, 2, 3],       
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

arr1_reshape=np.transpose(arr1)
result = arr1_reshape + arr2

print("Array arr1:")
print(arr1)
print("Array arr2:")
print(arr2)
print("Result after addition:")
print(result)


Array arr1:
[[2 3 4 5]]
Array arr2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Result after addition:
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [39]:
arr1 = np.array([[2],    
                  [3],
                  [4]])
arr2 = np.array([[5, 6, 7]])
result = arr1 + arr2

print("Array arr1:")
print(arr1)
print("Array arr2:")
print(arr2)
print("Result after addition:")
print(result)


Array arr1:
[[2]
 [3]
 [4]]
Array arr2:
[[5 6 7]]
Result after addition:
[[ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [40]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],   
                  [4, 5, 6]])
arr2 = np.array([[2, 3],      
                  [4, 5]])


arr2_reshaped = np.expand_dims(arr2, axis=2)  
result = arr1 * arr2_reshaped

print("Array arr1:")
print(arr1)v
print("\nArray arr2:")
print(arr2)
print("\nResult after multiplication:")
print(result)


SyntaxError: invalid syntax (1211687641.py, line 14)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-41 Calculate column wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])











 



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean=np.mean(arr,axis=0)
print("original array")
print(arr)
print("column wise mean")
print(column_mean)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
maximum=np.max(arr,axis=1)
print("original array")
print(arr)
print("maximum value")
print(maximum)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
maxi_indices=np.argmax(arr,axis=0)
print("original array")
print(arr)
print("maximum indices")
print(maxi_indices)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(row):
    cumsum = np.cumsum(row)  
    return cumsum
moving_sum_arr = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Array:")
print(arr)
print("Moving sum along rows:")
print(moving_sum_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
arr = np.array([[2, 4, 6], [4, 5, 7]])

are_all_even = np.all(arr % 2 == 0, axis=0)

print("Array:")
print(arr)
print("Are all elements in each column even?")
print(are_all_even)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE;-46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.



In [ ]:
def reshape_matrix(arr,m,n):
    return arr.reshape(m,n)

arr=np.array([1,2,3,4,5,6])
m=2
n=3
print("original array")
print(arr)
print("\nafter modified")
result=reshape_matrix(arr,m,n)
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-47 Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def flatten_matrix(input_matrix):
    return input_matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
result=flatten_matrix(input_matrix)
print("original array")
print(input_matrix)
print("\nafter modified")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-48. Write a function that concatenates two given arrays along a specified axis
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [ ]:
def concatenates_array(array1,array2,axis=0):
    return np.concatenate((array1,array2),axis=axis)

array1 = np.array([[1, 2], [3, 4]]) 
array2 = np.array([[5, 6], [7, 8]])

result_0=concatenates_array(array1,array2,axis=0)
result_1=concatenates_array(array1,array2,axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated arrays along axis 0:")
print(result_0)
print("\nConcatenated arrays along axis 1:")
print(result_1)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
def split_array(original_array,num_split,axis=0):
    return np.split(original_array,num_split,axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result_0=split_array(original_array,num_split=3,axis=0)
result_1=split_array(original_array,num_split=3,axis=1)

print("original array")
print(original_array)
print("\nsplit_array along axis 0:")
print(result_0)
print("\nsplit_array along axis 1:")
print(result_1)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [ ]:
import numpy as np

def insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):

    for idx, val in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, val)
        print(original_array)
    original_array = np.delete(original_array, indices_to_delete)
    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1=np.random.randint(1,100,size=(5,5))
arr2=np.arange(1,26)
arr2_reshaped = arr2.reshape(5,5)
result=arr1+arr2_reshaped
print("first array 1")
print(arr1)
print("second array 2")
print(arr2_reshaped)
print("sum of both array")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
result=arr2-arr1
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5 Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1=np.random.randint(1,100,size=(5,5))
arr2=np.arange(1,6)
result=arr1*arr2.reshape(-1,1)
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
result=arr1/arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1=np.arange(1,6)
arr2=np.arange(5,0,-1)
result=arr1**arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of exponentiation:")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
def count_substring(arr,substring):
    count=0
    for string in arr:
        count+=string.count(substring)
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring='world'
result=count_substring(arr,substring)
print("occurance of substring is=",result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
def uppercase_charactor(arr):
    uppercase_char=[]
    for string in arr:
        for char in string:
            if char.isupper(): 
                
                uppercase_char.append(char)
    return uppercase_char

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
all_char=uppercase_charactor(arr)v
print("uppercase character is =",all_char)

### QUE:-58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)


arr=np.array(['apple','banana','grape','pineapple'])
old_substring='apple'
new_substring='orange'
modified_arr=replace_substring(arr, old_substring, new_substring)
print("Modified array:")
print(modified_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-59. Write a function that concatenates strings in a NumPy array element-wise
arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])

In [ ]:
def concatenates_strings(arr1,arr2):
    concatenated_arr=np.char.add(arr1,arr2)
    return concatenated_arr
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_arr=concatenates_strings(arr1,arr2)
print(concatenated_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def longest_string(arr):
    max_lengh=0
    for string in arr:
        max_lengh=max(max_lengh,len(string))
    return max_lengh
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
maxx_lengh=longest_string(arr)
print(maxx_lengh)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
dataset=np.random.randint(1,1001,size=100)
mean=np.mean(dataset)
median=np.median(dataset)
variance=np.var(dataset)
std_deviation=np.std(dataset)
print("Dataset:")
print(dataset)
print("\nMean:", mean)
print("\nMedian:", median)
print("\nVariance:", variance)
print("\nStandard Deviation:", std_deviation)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

In [ ]:
arr=np.random.randint(1,101,size=50)
percentile_25=np.percentile(arr,25)
percentile_75=np.percentile(arr,75)v
print("Random numbers array:")
print(arr)
print("\n25th percentile:", percentile_25)
print("\n75th percentile:", percentile_75)

### QUE:-63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])
correlation_coefficient = np.corrcoef(array1, array2)[0,1]
print(correlation_coefficient)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:")
print(result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles

In [ ]:
array = np.random.randint(10, 1001, size=50)
percentiles = np.percentile(array, [10, 50, 90])
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("Array of 50 integers:")
print(array)
print("10th percentile:", percentiles[0])
print("Median (50th percentile):", percentiles[1])
print("90th percentile:", percentiles[2])
print("First quartile:", first_quartile)
print("Third quartile:", third_quartile)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
specific_element = 7
index = np.where(array == specific_element)
if len(index) > 0:
    print(f"The index of {specific_element} in the array is: {index[0]}")
else:
    print(f"{specific_element} is not present in the array.")

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-67. Generate a random NumPy array and sort it in ascending order

In [ ]:
random_array = np.random.rand(10)

sorted_array = np.sort(random_array)

print("Random array:\n", random_array)
print("\nSorted array in ascending order:\n", sorted_array)

-------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
filterd_arr=arr[arr>20]
print(filterd_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])

In [ ]:
arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("Elements divisible by 3:", filtered_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Elements between 20 and 40:", filtered_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])

In [ ]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Byte order of the array:", byte_order)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)v
print("Array after byte swapping:", arr)

### QUE:-73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped array:", swapped_arr)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = np.dtype(arr.dtype).byteorder

swapped_arr = arr.newbyteorder(system_endianness)

print("Original array:", arr)
print("Swapped array based on system endianness:", swapped_arr)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`  attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder
if byte_order != '=':
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.




In [ ]:
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.




In [ ]:
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999

print("Original matrix:")
print(matrix)
print("Modified view_slice:")
print(view_slice)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.



In [ ]:
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :]  


view_b += 5

print("Original array_a:")
print(array_a)
print(view_b)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.




In [ ]:
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.T

reshaped_view[0, 0] = 999

print("Original orig_array:")
print(orig_array)
print("Modified reshaped_view:")
print(reshaped_view)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.




In [ ]:
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 999
print("Original data:")
print(data)
print("\nModified data_copy:")
print(data_copy)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.




In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition_result = A + B
print("Addition result:")
print(addition_result)

subtraction_result = A - B
print("Subtraction result:")
print(subtraction_result)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.



In [ ]:
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
multiplication_result = np.dot(C, D)
print("Matrix multiplication result:")
print(multiplication_result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-83. Create a matrix `E` and find its transpose.



In [ ]:
E = np.random.randint(1, 10, size=(3, 3))

transpose_result = np.transpose(E)
print("Transpose of matrix E:")
print(transpose_result)


-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-84. Generate a square matrix `F` and compute its determinant.



In [ ]:
F = np.random.randint(1, 10, size=(3, 3))
determinant_result = np.linalg.det(F)
print("Determinant of matrix F:", determinant_result)

-------------------------------------------------------------------------------------------------------------------------------------

### QUE:-85. Create a square matrix `G` and find its inverse.

In [ ]:
G = np.random.randint(1, 10, size=(3, 3))

inverse_result = np.linalg.inv(G)
print("Inverse of matrix G:")
print(inverse_result)

-------------------------------------------------------------------------------------------------------------------------------------